#sharkygo.kv
<MenuScreen>:
    BoxLayout:
        orientation: 'vertical'
        Button:
            text: 'Start Game'
            on_press: root.manager.current = 'game'
        Button:
            text: 'Quit'
            on_press: app.stop()

<GameScreen>:
    SharkyGoGame:
        id: game

<SharkyGoGame>:
    shark: shark
    top_pipe: top_pipe
    bottom_pipe: bottom_pipe
    score: root.score
    canvas:
        Color:
            rgb: 0.2, 0.6, 1
        Rectangle:
            pos: self.pos
            size: self.size

    Shark:
        id: shark
        pos: root.width / 4, root.height / 2

    Pipe:
        id: top_pipe
        size: 70, 300
        pos: root.width, root.height - 300
    Pipe:
        id: bottom_pipe
        size: 70, 300
        pos: root.width, 0

    FloatLayout:
        size: root.size
        Label:
            text: str(root.score)
            font_size: 50
            bold: True
            color: 1, 1, 1, 1
            pos_hint: {"center_x": 0.5, "top": 1.4}

<Shark>:
    size: 50, 50
    canvas:
        Color:
            rgb: 0, 1, 0
        Ellipse:
            pos: self.pos
            size: self.size

<Pipe>:
    canvas:
        Color:
            rgb: 1, 0, 0
        Rectangle:
            pos: self.pos
            size: self.size