<MenuScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: 50  # ระยะห่างจากขอบ
        spacing: 20  # ระยะห่างระหว่างวิดเจ็ต
        canvas.before:
            Color:
                rgb: 0.2, 0.6, 0.8 
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: 'SharkyGo'
            font_size: 60
            bold: True
            color: 1, 1, 1, 1  # สีขาว
            size_hint_y: None
            height: 100

        Button:
            text: 'Start Game'
            font_size: 30
            bold: True
            background_color: 0.1, 0.5, 0.7, 1
            color: 1, 1, 1, 1
            size_hint_y: None
            height: 80
            on_press: root.manager.current = 'game'

        Button:
            text: 'Quit'
            font_size: 30
            bold: True
            background_color: 0.8, 0.2, 0.2, 1
            color: 1, 1, 1, 1 
            size_hint_y: None
            height: 80
            on_press: app.stop()

        Label:
            text: 'Created by สุดเทพ'
            font_size: 20
            color: 1, 1, 1, 1
            size_hint_y: None
            height: 50

<GameScreen>:
    SharkyGoGame:
        id: game

<SharkyGoGame>:
    shark: shark
    top_pipe: top_pipe
    bottom_pipe: bottom_pipe
    score: root.score
    canvas:
        Rectangle:
            pos: self.pos
            size: self.size
            source: root.background.source

    Shark:
        id: shark
        pos: root.width / 4, root.height / 2

    Pipe:
        id: top_pipe
        size: 70, 300
        pos: root.width, root.height - 300
    Pipe:
        id: bottom_pipe
        size: 70, 300
        pos: root.width, 0

    FloatLayout:
        size: root.size
        Label:
            text: str(root.score)
            font_size: 50
            bold: True
            color: 1, 1, 1, 1
            pos_hint: {"center_x": 0.5, "top": 1.4}

<Shark>:
    size_hint: None, None
    size: 70, 50
    canvas:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'assets/images/shark.png'

<Pipe>:
    canvas:
        Color:
            rgb: 1, 0, 0
        Rectangle:
            pos: self.pos
            size: self.size